<?php
namespace EmailSettings;

class CustomEmail
{

    /*
        [FOR THEME INTEGRATION]
        Sends custom E-Mail formed from argumnets passed to function

        @param $args - an array of args passed to function to generate E-Mail from
    
        $args["variables"] - OPTIONAL|ARRAY - the array of variables like %VARIABLE% that will be replaced with actual values in E-Mail message, by default - array("%USERNAME%","%EMAIL%","%LINK%")

        $args["user"] - REQUIRED|WP_USER - an user object we are acting on (i.e changing password/email/etc.)

        $args["url"] - OPTIONAL|STRING - a custom URL that will be used in E-Mail letter (i.e activation url/reset password url/etc.)

        $args["title-option"] - OPTIONAL|STRING - the name of setting field to get e-mail title/subject from

        $args["title"] - OPTIONAL|STRING - the actual title/subject used if @param title-option is not passed

        
        $args["variables_values"] - OPTINAL|ARRAY - the array of variables values to be put in E-Mail message, by default - array($user->user_login,$user->user_email,"<a href='".$url."'>".$url."</a>")

        $args["fallback_message"] - OPTINAL|STRING - the message that will be used as a fallback, i.e in case when E-mail message is empty

        $args["wp_mail_from_name"] - OPTONAL|STRING - the function name that will be used to filter the email sender name

        $args["wp_mail_from_name"] - OPTINAL|STRING - the function name that will be used to filter the email sender E-Mail address

        $args["email_settings_mail_action"] - OPTINAL|STRING - the function name that will be executed on PHPMailer callback

        @returns BOOLEAN
    */
    public static function generate(array $args)
    {
        /*
            Declare basic variables
        */
        $url = isset($args["url"]) ? $args["url"] : "";
        $user = isset($args["user"]) ? $args["user"] : null;

        if(is_null($user))
        {
            throw new \Exception(__("User can not be null! You must pass user object to use custom E-MailSettings functions!"));
            
        }
        /*
            Get & generate custom activation E-Mail
        */
        /*
            Get custom message
        */
        $message = base64_decode(get_option($args["message-option"]));
        /*
            Get custom title & define a fallback
        */
        $title = "An E-Mail subject generated by EmailSettings plugin";
        if(isset($args["title-option"]) && strlen($args["title-option"]) > 0)
        {
            $title = esc_html(get_option($args["title-option"]));
        }
        else if(isset($args["title"]) && strlen($args["title"]) > 0)
        {
            $title = sanitize_text_field($args["title"]);
        }
        /*
            Replace variables in text with data
        */
        $search_arr = isset($args["variables"]) ? $args["variables"] : array(); 
        $replace_arr = array($user->user_login,$user->user_email,"<a href='".$url."'>".$url."</a>");
        /*
            Use custom variables values passed as argument
        */
        if(isset($args["variables_values"]) && is_array($args["variables_values"]) && sizeof($args["variables_values"]) > 0)
        {
            $replace_arr = $args["variables_values"];
        }
        $message = str_replace($search_arr,$replace_arr,$message);

        /*
            Fallback for message
        */
        if(strlen($message) == 0)
        {
            $message = isset($args["fallback_message"]) ? $args["fallback_message"] : __("This E-Mail is generated with E-Mail settings plugin, but it seems like the custom E-Mail method was used with incorrect arguments.");
        }
        return self::send_email($args,$user,$title,$message);
    }
    /*
        Sends the email according to provided argumnets

        @param $args - an array of argumnets passed to function (needed for filters & actions applied/executed before wp_mail function)

        @param $user - an user object we act on

        @param $title - the title/subject of e-mail letter

        @param $message - the message / body of e-mail letter

        @returns BOOLEAN
    */
    protected static function send_email($args,$user,$title,$message)
    {
        /*
           Apply filters
        */
        if(isset($args["wp_mail_from_name"]) && strlen($args["wp_mail_from_name"]) > 0)
        {
            add_filter('wp_mail_from_name', $args["wp_mail_from_name"]);
        }
        if(isset($args["wp_mail_from"]) && strlen($args["wp_mail_from"]) > 0)
        {
            add_filter('wp_mail_from', $args["wp_mail_from"]);
        }
        /*
            Add a PHPMailer callback function if it is set
        */
        if(isset($args["email_settings_mail_action"]))
        {
            add_action( "email_settings_mail_action", $args["email_settings_mail_action"] );
        }
        /*
            Send E-Mail
        */
        $result = wp_mail($user->user_email, $title, $message);
        /*
            Remove filters
        */
        if(isset($args["wp_mail_from_name"]) && strlen($args["wp_mail_from_name"]) > 0)
        {
            remove_filter('wp_mail_from_name', $args["wp_mail_from_name"]);
        }
        if(isset($args["wp_mail_from"]) && strlen($args["wp_mail_from"]) > 0)
        {
            remove_filter('wp_mail_from', $args["wp_mail_from"]);
        }

        return $result;
    }
}